<?php
/**
 * Created by PhpStorm.
 * User: Allen
 * Date: 21/12/2016
 * Time: 3:23 PM
 */

namespace summic\authclient;

class Module extends \yii\base\Module
{

    public $userFieldMap = array(
        'username'      => 'username',
        'email'         => 'email',
        'password_hash' => 'password_hash',
    );

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}